#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["Tracker/Tracker.csproj", "Tracker/"]
RUN dotnet restore "Tracker/Tracker.csproj"
COPY . .
WORKDIR "/src/Tracker"
RUN dotnet build "Tracker.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Tracker.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Tracker.dll"]